### ISSUE TITLE
command not found: dart2js

### ISSUE THREAD

**Issue by huang12zheng** [mpflutter/mpflutter.github.io#4]
Do you mean that `dart compile js --version`
to show
`Dart-to-JavaScript compiler (dart2js) version: 2.18.5`?

Flutter version 3.3.9 on channel stable at
[install macos](https://github.com/mpflutter/mpflutter.github.io/blob/d6d0a868321598eaf3aff3d73d7cc3432eca2d29/docs/2-install-macos.md)

**Comment by huang12zheng** [comment]
I found https://github.com/mpflutter/mpflutter/issues/255.
So, maybe the documentation needs to be modified

**Comment by PonyCui** [comment]
如果使用 mpflutter 0.18.0 以上版本，不需要 dart2js，只需要 dart 就可以了。

**Comment by PonyCui** [comment]
相关文档已更新
